//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_wheelchair : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean FirstButton
        {
            get
            {
                return SteamVR_Actions.wheelchair_FirstButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean SecondButton
        {
            get
            {
                return SteamVR_Actions.wheelchair_SecondButton;
            }
        }
        
        public virtual SteamVR_Action_Vector2 JoyStick
        {
            get
            {
                return SteamVR_Actions.wheelchair_JoyStick;
            }
        }
        
        public virtual SteamVR_Action_Single FirstButtonAnalog
        {
            get
            {
                return SteamVR_Actions.wheelchair_FirstButtonAnalog;
            }
        }
        
        public virtual SteamVR_Action_Boolean JoystickTouched
        {
            get
            {
                return SteamVR_Actions.wheelchair_JoystickTouched;
            }
        }
    }
}
